### ISSUE TITLE
WATT version of proc_macro in cqrs-codegen crate

### ISSUE THREAD

**Issue by tyranron** [instrumentisto/cqrs-rs#3]
To reduce compilation time and ensure safety via sandboxing, let's provide a [watt](https://docs.rs/watt) version of our `cqrs-codegen` crate.

How it would work:
1. Create a `no-watt` feature for `cqrs-codegen` crate. So, by default the compilation will use `watt`, but a usual compilation may be opt-in if desirable.
2. Make all dependencies of `cqrs-codegen` crate optional behind `no-watt` feature.
3. Create a `build.rs` which compiles `cqrs-codegen` crate into `src/codegen.wasm` if it's absent.
4. Setup correct conditional compilation in `src/lib.rs`.
5. Re-export `no-watt` feature in `cqrs` crate as `codegen/no-watt`.
6. ...
7. PROFIT

Let's do it right after completing #2

**Comment by tyranron** [comment]
Consider https://github.com/rust-lang/cargo/issues/4881 tricks for building `codegen.wasm`.

**Comment by ffuugoo** [comment]
Seen watt announcement few weeks ago. This is rad. 👍
